# -*- coding: utf-8 -*-
"""week1_eda_preprocessing.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Cf0baQfzr3xFV-u2hnKAZMIhPt5dGQL

# WEEK 1: CROP DISEASE DETECTION USING CNN

# INSTALL REQUIRED LIBRARIES
"""

!pip install tensorflow opencv-python matplotlib seaborn scikit-learn pillow -q

"""# IMPORT LIBRARIES"""

import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time # Import the time module

from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator

start_time = time.time() # Define start_time here

"""# UPLOAD DATASET ZIP FILE"""

from google.colab import files

uploaded = files.upload()

"""# EXTRACT ZIP FILE"""

import zipfile

zip_filename = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall('/content/dataset')

print("Dataset Extracted Successfully")

"""# CHECK DATASET PATH"""

import os

dataset_path = "/content/dataset/PlantVillage"

categories = os.listdir(dataset_path)

print("Total Classes:", len(categories))
print(categories[:10])

"""# DISPLAY SAMPLE IMAGES"""

import matplotlib.pyplot as plt
import cv2

plt.figure(figsize=(12,12))

for i, category in enumerate(categories[:9]):

    path = os.path.join(dataset_path, category)

    img_name = os.listdir(path)[0]

    img_path = os.path.join(path, img_name)

    image = cv2.imread(img_path)

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    plt.subplot(3,3,i+1)

    plt.imshow(image)

    plt.title(category)

    plt.axis("off")

plt.tight_layout()
plt.show()

"""# CLASS DISTRIBUTION ANALYSIS"""

import pandas as pd

class_counts = {}

for category in categories:

    path = os.path.join(dataset_path, category)

    class_counts[category] = len(os.listdir(path))

df = pd.DataFrame({
    "Class": class_counts.keys(),
    "Count": class_counts.values()
})

df = df.sort_values(by="Count", ascending=False)

print(df.head())

plt.figure(figsize=(18,6))

plt.bar(df["Class"], df["Count"])

plt.xticks(rotation=90)

plt.title("Class Distribution")

plt.xlabel("Classes")

plt.ylabel("Number of Images")

plt.show()

"""# IMAGE PREPROCESSING"""

import os

IMG_SIZE = 224

image_filepaths = []
image_labels = []

dataset_path = "/content/dataset/PlantVillage"
categories = os.listdir(dataset_path)

NUM_CLASSES = len(categories)

print("Gathering image filepaths and labels...")

for category in categories:
    path = os.path.join(dataset_path, category)
    if not os.path.isdir(path):
        print(f"Warning: {path} is not a directory. Skipping.")
        continue

    for img_filename in os.listdir(path):
        img_path = os.path.join(path, img_filename)
        if not os.path.isfile(img_path):
            print(f"Warning: {img_path} is not a file. Skipping.")
            continue
        image_filepaths.append(img_path)
        image_labels.append(category)

print(f"Total image paths gathered: {len(image_filepaths)}")
print("Image path gathering completed. Proceeding to create DataFrame and split data.")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming image_filepaths and image_labels are populated from the previous cell (-eRD51qtk43U)

image_df = pd.DataFrame({
    'filepath': image_filepaths,
    'label': image_labels
})

print("Created DataFrame of image paths and labels.")
print("DataFrame head:")
print(image_df.head())

# Split the DataFrame into training, validation, and test sets
train_df, temp_df = train_test_split(
    image_df,
    test_size=0.30, # 30% for temp (val+test)
    random_state=42,
    stratify=image_df['label']
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50, # 50% of temp_df for test, 50% for val (so 15% val, 15% test of original)
    random_state=42,
    stratify=temp_df['label']
)

print(f"Training set size: {len(train_df)} samples")
print(f"Validation set size: {len(val_df)} samples")
print(f"Testing set size: {len(test_df)} samples")

# Print DataFrame shapes as they are now the 'data'
print("Training DataFrame shape:", train_df.shape)
print("Validation DataFrame shape:", val_df.shape)
print("Testing DataFrame shape:", test_df.shape)

# The original X and y as NumPy arrays are no longer created to avoid memory issues.

# Data splitting is now handled in the previous cell (sHHyXvUwPjMw)
# The original content of this cell is removed to prevent redundant operations and NameErrors.

from tensorflow.keras.preprocessing.image import ImageDataGenerator

BATCH_SIZE = 32 # Define a batch size

train_datagen = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    width_shift_range=0.2,
    height_shift_range=0.2,
    rescale=1./255 # Normalize images for training
)

val_test_datagen = ImageDataGenerator(
    rescale=1./255 # Only normalize for validation and testing
)

# Assuming train_df, val_df, test_df are available from sHHyXvUwPjMw
# And IMG_SIZE, NUM_CLASSES from -eRD51qtk43U

train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='filepath',
    y_col='label',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical', # Use 'categorical' for one-hot encoded labels
    shuffle=True,
    seed=42
)

val_generator = val_test_datagen.flow_from_dataframe(
    dataframe=val_df,
    x_col='filepath',
    y_col='label',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False, # No need to shuffle validation data
    seed=42
)

test_generator = val_test_datagen.flow_from_dataframe(
    dataframe=test_df,
    x_col='filepath',
    y_col='label',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False, # No need to shuffle test data
    seed=42
)

print("Data Augmentation and Generators Ready.")
# Note: train_generator.num_classes is not a direct attribute. Using NUM_CLASSES defined earlier.
print("Train Generator created with", train_generator.n, f"images in {NUM_CLASSES} classes.")
print("Validation Generator created with", val_generator.n, f"images in {NUM_CLASSES} classes.")
print("Test Generator created with", test_generator.n, f"images in {NUM_CLASSES} classes.")
print("Note: A UserWarning about an invalid image filename was reported for the validation generator, which indicates one file was skipped.")

import cv2
import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))

# Get the filepath and label for the first image in the training DataFrame
first_image_filepath = train_df['filepath'].iloc[0]
first_image_label = train_df['label'].iloc[0]

# Load the image using OpenCV
image = cv2.imread(first_image_filepath)

# Convert BGR to RGB if image is not None
if image is not None:
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    plt.imshow(image)
    plt.title(first_image_label)
    plt.axis("off")
else:
    print(f"Could not load image: {first_image_filepath}")

plt.show()

# The X_train, X_val, X_test, y_train, y_val, y_test NumPy arrays are no longer created
# as data is now handled by ImageDataGenerators for memory efficiency.
# This cell is no longer needed for saving these arrays.

print("Testing Data:", test_df.shape)

# np.save('/content/X_train.npy', X_train) np.save('/content/X_val.npy', X_val) np.save('/content/X_test.npy', X_test) np.save('/content/y_train.npy', y_train) np.save('/content/y_val.npy', y_val) np.save('/content/y_test.npy', y_test) print("Processed Data Saved Successfully")

print("===================================")
print(" DATASET SUMMARY ")
print("===================================")

print("Total Classes:", len(categories))

print("Total Images:", len(image_df))

print("Training Images:", len(train_df))

print("Validation Images:", len(val_df))

print("Testing Images:", len(test_df))

print("========================================")
print(" WEEK 1 TASKS COMPLETED SUCCESSFULLY ")

end_time = time.time()

print("Execution Time:",
      round((end_time - start_time)/60, 2),
      "minutes")

print(" READY FOR WEEK 2 - CNN MODEL BUILDING ")

print("======================================")
print(" PROJECT STATUS ")
print("======================================")

print("Project Name: Crop Disease Detection")

print("Week 1 Status: COMPLETED")

print("Next Step: CNN Model Training")

# X_train.npy
# X_val.npy
# X_test.npy

# y_train.npy
# y_val.npy
# y_test.npy